### PR TITLE
Add More Resources To QRack Introduction Doc

### PR DESCRIPTION
**Pull request by WingCode**
1.  This talk can be probably linked into QRack docs because it gives an alternative introduction (albeit a visual one) to the one given over here https://qrack.readthedocs.io/en/latest/index.html .
2. There is a nice pictorial overview of QRack layers at https://youtu.be/yxyqJDC4SUo?t=683 which I couldn't find in QRack documentation.
3. I think we are not covering https://github.com/vm6502q/OpenRelativity & https://github.com/twobombs/thereminq in the qrack doc introduction https://qrack.readthedocs.io/en/latest/index.html. I think both of them are cool use-cases of QRack and probably we garner more interest from the community by including them.

### CODE REVIEW

**Comment by WingCode** [comment]
@WrathfulSpatula Point 2 is not addressed. Please feel free to provide the image/commit it

**Comment by WrathfulSpatula** [comment]
@WingCode Thank you so much for the PR! The documentation definitely benefits from what you've done!

I've added `Qrack_Org_Chart.png` over in b815b12. Would you like to find a place to incorporate it in your draft branch, or should I give it written context, first?

(Thanks again!)

**Comment by WingCode** [comment]
@WrathfulSpatula (Happy to help!)
If you could provide a written context about the diagram, that would be really helpful since there are some acronyms in the diagram which might be intimating for a new user in QRack. Please feel free to incorporate the image and the written context as part of this PR.

**Comment by WrathfulSpatula** [comment]
@WingCode Sorry for moving slowly on this. (I had an exceptionally busy week at work.) However, does fbfc3b5 help? You could merge my branch into your draft, and feel free to change it in any way you need.

**Comment by WrathfulSpatula** [comment]
Or, I could finish this up. Just let me know!

**Comment by WingCode** [comment]
No problems! The write-up LGTM. Now, we will have even more context for new users getting into QRack :)
Yes, I can merge the branch into draft.

**Review by WrathfulSpatula — APPROVED** [review]
@WingCode Thanks again! I'm merging this myself because, many years ago, we created two copies of this documentation at two slightly different URLs, and I need to merge this into the other repo, as well. (It was a mistake that Benn Bollay and I decided to address by maintaining both repositories, but maybe someone else has a better idea.)

**Pull request merged**
